### ISSUE TITLE
Tag specific stickers by replying to them

### ISSUE THREAD

**Issue by Nukesor** [Nukesor/sticker-finder#14]

**Comment by pressRtowin** [comment]
this is not currently working in the live version

**Comment by Nukesor** [comment]
Just tested it and it seem to work. You still need to reply with `/tag` or `/replace` though.
I thought a lot about, whether the command should be necessary or not, but in the end it get's really confusing in the code base, if I don't use commands.

**Comment by Nukesor** [comment]
I furthermore added a support group in telegram and added the link in the start/donation and help text. This should make bug reporting easier in the future, even though Github is a lot more convenient ;)

**Comment by pressRtowin** [comment]
I was trying this in a group that had the bot added as an admin and whenever I tried to /tag or /replace via reply, it'd just write to the tags of the last sticker sent

**Comment by Nukesor** [comment]
Interesting. In only tried to reproduce this in private chats. Let me check this out real quick.

**Comment by Nukesor** [comment]
I'm still having trouble to reproduce this behaviour:
![image](https://user-images.githubusercontent.com/3322822/61892117-683f7100-af0b-11e9-89eb-28e70f3396cc.png)
![image](https://user-images.githubusercontent.com/3322822/61892150-7ee5c800-af0b-11e9-93c4-d76dc08b5ff0.png)

Was there anything you can think of, that could have triggered this kind of behavior?

**Comment by pressRtowin** [comment]
I can't think of anything off the top of my head. Let me look at the chat history.

**Comment by pressRtowin** [comment]
I think I figured it out. I was trying to /replace or /tag a sticker in a pack that hadn't been reviewed yet. Doing so doesn't provide any feedback and automatically defaults to modifying the tags of the last sticker from a supported pack sent.

**Comment by Nukesor** [comment]
Ahhh :D. This might be the case. I'll look into this right away!
