### ISSUE TITLE
Bug in replace_single

### ISSUE THREAD

**Issue by patrickjmccarty** [Nukesor/sticker-finder#22]
stickerfinder/telegram/commands/tag.py has a bug in replace_single:
`text = update.message.text[4:]`
should be:
`text = update.message.text[8:]`
because the /replace command is 4 characters longer than /tag. This was causing the replace feature to add a tag for lace.

Also update the `# Remove the /tag command` comment above it that mentions /tag.

**Comment by Nukesor** [comment]
Oh boy. Thanks! That's probably a copy paste bug from the `/tag` functionality :D
