### ISSUE TITLE
Tag limit not made clear to users

### ISSUE THREAD

**Issue by patrickjmccarty** [Nukesor/sticker-finder#24]
I realized after tagging some stickers that the bot was only saving the first 10 tags and silently dropping the rest. It was easy to comment out the line that did that, but was somewhat annoying that I had already entered tags that were lost. If users attempt to send more than the maximum number of tags, it should probably send them a message indicating that the tags were discarded and they are limited to N tags.

**Comment by Nukesor** [comment]
This is probably a good solution.
Anyway sending more than 10 tags is a strong indicator for malicious behavior.

Stickers can usually be well described with 5 or less tags.
A notification about too many tags could be helpful though. Malicious users could be banned by hand anyway through the maintenance user tag check tasks.
