### ISSUE TITLE
Add toggle command for fur and nsfw

### ISSUE THREAD

**Issue by TilCreator** [Nukesor/sticker-finder#31]
If one wants to see nsfw and/or fur stickers it is quite irritating to always add these tags to the query.
My suggestion is to add a toggle command for those tags, so that fur and/or nsfw tagged stickers are not automatically hidden.

**Comment by Nukesor** [comment]
I like this. This definitely makes things a little more convenient for users, which use these flags a lot.
The keywords should keep working as they do now, for anyone that doesn't want to search for this stuff all the time.
