### ISSUE TITLE
Translate sticker emojis to tags

### ISSUE THREAD

**Issue by TilCreator** [Nukesor/sticker-finder#32]
This should remove unnecessary double tagging, like ":blush:" and "blush", and gives many untagged stickers at least one tag.

Here is a list (from Telegram Source Code) that converts unicode emoji codes to alpha (short names / tags).
https://raw.githubusercontent.com/Telegram-FOSS-Team/emoji_codegen/master/emoji_autocomplete.json
For example ":cool:" to "\:\cool\:\" (ignore "\\", found no other way to write this in MD) which could be used to get the tag "cool".
Emoji to List key function:
```python
def emoji_to_list_key (emoji):
    chars = []
    for char in emoji:
        char_encoded = f'{ord(char):X}'.lower()

        if char_encoded not in [*[f'fe0{i:X}'.lower() for i in range(16)], '200d']:  # Ignore Unicode VARIATION SELETORs and ZERO WIDTH JOINER
            chars.append(char_encoded)

    return '-'.join(chars)
```

**Comment by Nukesor** [comment]
That's a cool idea! There are many descriptions that are quite verbose e.g. `right arrow curving left` or 
`woman in lotus position: medium skin tone`. This would definitely need to be cleaned up.

**Comment by TilCreator** [comment]
There are some unprintable emojis, skin tones for example, so cleanup is a must.

**Comment by TilCreator** [comment]
Why the close?

**Comment by Nukesor** [comment]
I found, that many stickers have emojis, that don't really match the sticker's content.
I don't think that this will be an enrichment for the database. It'll probably rather degrade the quality of tags (there are a LOT of stickers and quite few emojis, 1000+ stickers per emoji)

On top of this, I kinda stopped improving StickerFinder (despite occasional bug fixes).

**Comment by TilCreator** [comment]
OK
